import 'package:flutter_riverpod/flutter_riverpod.dart';

class HomeScreenModel {
  final List<String> period;
  final List<String> section;
  final List<String> characterList;

  HomeScreenModel({
    this.period = const ['v1.10', 'v1.11', '최근 3일 (v1.11)', '최근 7일 (v.1.11)'],
    this.section = const [
      'in 1000',
      '미스릴+',
      '다이아1+',
      '다이아2+',
      '다이아몬드+',
      '플래티넘+',
      '플래티넘',
      '골드',
      '실버',
      '브론즈',
      '아이언'
    ],
    this.characterList = const [
      '재키',
      '아야',
      '피오라',
      '매그너스',
      '자히르',
      '나딘',
      '현우',
      '하트',
      '아이솔',
      '리 다이린',
      '유키',
      '혜진',
      '쇼우',
      '키아라',
      '시셀라',
      '실비아',
      '아드리아나',
      '쇼이치',
      '엠마',
      '레녹스',
      '로지',
      '루크',
      '캐시',
      '아델라',
      '버니스',
      '바바라',
      '알렉스',
      '수아',
      '레온',
      '일레븐',
      '리오',
      '윌리엄',
      '니키',
      '나타폰',
      '얀',
      '이바',
      '다니엘',
      '제니',
      '카밀로',
      '클로에',
      '요한',
      '비앙카',
      '셀린',
      '에키온',
      '마이',
      '에이든',
      '라우라',
      '띠아',
      '펠릭스',
      '엘레나',
      '프리야',
      '아디나',
      '마커스',
      '칼라',
      '에스텔',
      '피올로',
      '마르티나',
      '헤이즈',
      '아이작',
      '타지아',
      '이렘',
      '테오도르',
      '이안',
      '바냐',
      '데비&마를렌',
      '아르다',
      '아비게일',
      '알론소',
      '레니',
      '츠바메',
      '케네스',
      '카티야',
      '샬럿',
    ],
  });

  HomeScreenModel copyWith({
    List<String>? period,
    List<String>? section,
    List<String>? characterList,
  }) {
    return HomeScreenModel(
      period: period ?? this.period,
      section: section ?? this.section,
      characterList: characterList ?? this.characterList,
    );
  }
}
